#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportMaster
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sportmaster")]
	public partial class MainDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MainDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["sportmasterConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MainDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MainDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MainDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MainDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Offer> Offers
		{
			get
			{
				return this.GetTable<Offer>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAddPost")]
		public int spAddPost([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> uid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string social, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string pic, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string lname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uid, social, pic, fname, lname);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spSharePost")]
		public int spSharePost([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> uid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string social, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string pic, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> postuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uid, social, pic, postuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAddUser")]
		public int spAddUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> uid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string social, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string lname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uid, social, fname, lname);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAddOffer")]
		public int spAddOffer([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(256)")] string vk_uid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(256)")] string vk_sid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(256)")] string vk_lead_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(256)")] string vk_hash)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vk_uid, vk_sid, vk_lead_id, vk_hash);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAddStatistic")]
		public int spAddStatistic([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> uid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string social, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string ev)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uid, social, ev);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Offers")]
	public partial class Offer
	{
		
		private string _vk_uid;
		
		private string _vk_sid;
		
		private string _vk_lead_id;
		
		private string _vk_hash;
		
		private System.DateTime _cdate;
		
		public Offer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vk_uid", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string vk_uid
		{
			get
			{
				return this._vk_uid;
			}
			set
			{
				if ((this._vk_uid != value))
				{
					this._vk_uid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vk_sid", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string vk_sid
		{
			get
			{
				return this._vk_sid;
			}
			set
			{
				if ((this._vk_sid != value))
				{
					this._vk_sid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vk_lead_id", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string vk_lead_id
		{
			get
			{
				return this._vk_lead_id;
			}
			set
			{
				if ((this._vk_lead_id != value))
				{
					this._vk_lead_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vk_hash", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string vk_hash
		{
			get
			{
				return this._vk_hash;
			}
			set
			{
				if ((this._vk_hash != value))
				{
					this._vk_hash = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdate", DbType="DateTime NOT NULL")]
		public System.DateTime cdate
		{
			get
			{
				return this._cdate;
			}
			set
			{
				if ((this._cdate != value))
				{
					this._cdate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
